# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14748df19d5ea1c6fd6469ceb9a2a8b7cba7eba6ff2bd1d21f6712c460ec6c5e33b4312544fd13a83447d3be586417f19b00dde30724a888a96a134be3185a14

test:
  secret_key_base: 1bc67462e36d6c37adff5ea8c7dda24e25ed58b1d0c0624b32cfd4702d79c5f13beb3638a079383789fcf6ba6e2bd61d6665106058010ff0100bec2b170664c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
